apiVersion: redhatgov.io/v1alpha1
kind: TsscPipeline
metadata:
  name: sp-{{ pipeline_name }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "90"
spec:
  appName: ref-quarkus-mvn-jenkins-std
  serviceName: fruit
  appRepo:
    sourceUrl: http://github.com/adamgoossens/reference-quarkus-mvn_jenkins_workflow-standard.git
    destinationRepoName: reference-quarkus-mvn_jenkins_workflow-standard
  helmRepo:
    sourceUrl: http://github.com/adamgoossens/reference-quarkus-mvn-cloud-resources_jenkins_workflow-standard.git
    destinationRepoName: reference-quarkus-mvn-cloud-resources_jenkins_workflow-standard
  autoStartPipeline: false
