---
- name: acs - get central route
  kubernetes.core.k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    namespace: stackrox
    name: central
  register: central_route

- set_fact:
    init_bundle_name: "{{ cluster_name }}-init-bundle"

- name: acs - check if init bundle secret exists
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    namespace: helms-deep
    name: "{{ init_bundle_name }}"
  register: ib_secret

- when:
    - (ib_secret.resources | length > 0)
  set_fact:
    helm_ib_data: "{{ ib_secret.resources[0].data.helm | b64decode | from_yaml }}"

- when:
    - (ib_secret.resources | length == 0)
  block:
    - name: acs - generate init bundle
      uri:
        url: "https://{{ central_route.resources[0].spec.host }}/v1/cluster-init/init-bundles"
        force_basic_auth: true
        url_password: "{{ stackrox_admin_credential }}"
        url_username: "admin"
        method: POST
        validate_certs: false
        body:
          name: "{{ init_bundle_name }}"
        body_format: json
      register: init_bundle_api_result

    - set_fact:
        bundle_data: "{{ init_bundle_api_result.json }}"

    - name: acs - store init bundle
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            namespace: helms-deep
            name: "{{ init_bundle_name }}"
          stringData:
            expiry: "{{ bundle_data.meta.expiresAt }}"
          data:
            helm: "{{ bundle_data.helmValuesBundle }}"
            kubectl: "{{ bundle_data.kubectlBundle }}"

    - set_fact:
        helm_ib_data: "{{ bundle_data.helmValuesBundle | b64decode | from_yaml }}"

- set_fact:
    helm_values:
      centralEndpoint: "{{ central_route.resources[0].spec.host }}:443"
      clusterName: "{{ cluster_name }}"
      imagePullSecrets:
        allowNone: true

- name: "acs - {{ cluster_name }} - ensure stackrox namespace exists"
  kubernetes.core.k8s:
    kubeconfig: "{{ cluster_kubeconfig|default(omit) }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: stackrox

- name: "acs - {{ cluster_name }} - deploy or remove ACS collector services on this cluster"
  kubernetes.core.helm:
    kubeconfig: "{{ cluster_kubeconfig|default(omit) }}"
    name: stackrox-secured-cluster-services
    chart_ref: "{{ acs.collector.chart_ref }}"
    release_namespace: stackrox
    release_values: "{{ helm_ib_data | combine(acs.collector.helmValues|default({})) | combine(helm_values) }}"
    wait: true
    state: "{{ state|default('present') }}"
