apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: kafka-connect
  namespace: {{ namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "40"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    strimzi.io/use-connector-resources: "true"
spec:
  image: "quay.io/agoossen/kafka-connect-camel:1.6.2-3"
  bootstrapServers: 'kafka-kafka-bootstrap:9093'
  config:
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
  version: 2.6.0
  tls:
    trustedCertificates:
      - secretName: kafka-cluster-ca-cert
        certificate: ca.crt
  replicas: 1
  externalConfiguration:
    volumes:
      - name: connector-config
        secret:
          secretName: aws-credentials

