- when:
  - k8s_api_key is not defined
  block:
  - name: k8s - get kubernetes auth token
    community.okd.openshift_auth:
      host: "{{ host }}"
      validate_certs: "{{ validate_certs }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: k8s_auth_results

  - set_fact:
      k8s_api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
