ansible_tower_url: https://aap.adamgoossens.com

acm:
  gitopsRepoUrl: 'https://github.com/adamgoossens/helms-deep-resources.git'

sso:
  groupsToCreate:
    - allclusters-cluster-admins
    - allclusters-auditors
  usersToCreate: []

rbac:

namespaces:
  - { name: helms-deep, displayName: "HELMS DEEP" }
  - { name: advanced-cluster-security, displayName: "HELMS DEEP Advanced Cluster Security" }
  - { name: open-cluster-management, displayName: "HELMS DEEP Advanced Cluster Management" }
  - { name: helms-deep-sso, displayName: "HELMS DEEP Single Sign On" }
  - { name: helms-deep-registry-prod, displayName: "HELMS DEEP Production Registry" }
  - { name: helms-deep-eck, displayName: "HELMS DEEP ECK Cluster" }
  - { name: openshift-storage, displayName: "HELMS DEEP Storage" }

catalogSources: []

subscriptions:
  - name: rhacs-operator
    namespace: openshift-operators
    channel: latest

  - name: awx-resource-operator
    namespace: helms-deep
    channel: release-0.1

  - name: advanced-cluster-management
    namespace: open-cluster-management
    channel: release-2.3

  - name: group-sync-operator
    namespace: helms-deep-sso
    source: community-operators
    channel: alpha

  - name: ocs-operator
    channel: stable-4.7
    namespace: openshift-storage

  - name: quay-operator
    channel: quay-v3.5
    namespace: openshift-operators

  - name: rhsso-operator
    channel: alpha
    namespace: helms-deep-sso
