ansible_tower_url: https://aap.adamgoossens.com

services:
  acm: True
  acs: True
  sso: True
  aap: True

acm:
  gitopsRepoUrl: 'https://github.com/adamgoossens/helms-deep-resources.git'

sso:
  groupsToCreate:
    - allclusters-cluster-admins
    - allclusters-auditors
  usersToCreate:
    - username: alex-cluster-admin
      firstName: Alex
      lastName: Admin

    - username: shane-auditor
      firstName: Shane
      lastName: Auditor

    - username: chris-security
      firstName: Chris
      lastName: Security

namespaces:
  - { name: helms-deep, displayName: "HELMS DEEP" }
  - { name: advanced-cluster-security, displayName: "Advanced Cluster Security" }
  - { name: open-cluster-management, displayName: "Advanced Cluster Management" }
  - { name: helms-deep-sso, displayName: "Single Sign On" }
  - { name: helms-deep-registry-prod, displayName: "Production Registry" }
  - { name: helms-deep-eck, displayName: "ECK Cluster" }
  - { name: openshift-storage, displayName: "Storage" }
  - { name: mcs-secrets, displayName: "Managed Cluster Artifacts" }
  - { name: ansible-automation-platform, displayName: "Ansible Automation Platform" }

catalogSources: []

subscriptions:
  - name: openshift-pipelines-operator-rh
    namespace: openshift-operators
    channel: stable

  - name: rhacs-operator
    namespace: openshift-operators
    channel: latest

  - name: advanced-cluster-management
    namespace: open-cluster-management
    channel: release-2.4

  - name: group-sync-operator
    namespace: helms-deep-sso
    source: community-operators
    channel: alpha

  - name: odf-operator
    channel: stable-4.9
    namespace: openshift-storage

  - name: rhsso-operator
    channel: alpha
    namespace: helms-deep-sso

  - name: quay-operator
    channel: stable-3.6
    namespace: openshift-operators

  - name: ansible-automation-platform-operator
    channel: stable-2.1
    namespace: ansible-automation-platform
