---
- name: "get cluster DNS from satellite cluster {{ cluster_name }}"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ cluster_secret['kubeconfig'] }}"
    api_version: config.openshift.io/v1
    kind: DNS
    namespace: openshift-config
    name: cluster
  register: cluster_dns

- set_fact:
    sat_cluster_basedomain: "{{ cluster_dns.resources[0].spec.baseDomain }}"

- include_tasks: "tasks/sso/create-client-and-secret.yaml"
  vars:
    clientName: "{{ cluster_name }}-cluster"
    rootUrl: 'https://console-openshift-console.apps.{{ sat_cluster_basedomain }}'
    validRedirectURIs:
      - 'https://console-openshift-console.apps.{{ sat_cluster_basedomain }}/*'
      - 'https://api.{{ sat_cluster_basedomain }}/*'
      - 'https://oauth-openshift.apps.{{ sat_cluster_basedomain }}/*'

- module_defaults:
    kubernetes.core.k8s:
      kubeconfig: "{{ cluster_secret['kubeconfig'] }}"
    kubernetes.core.k8s_info:
      kubeconfig: "{{ cluster_secret['kubeconfig'] }}"
  block:
    - include_tasks: "tasks/sso/configure-oauth-oidc.yaml"
      vars:
        clientId: "{{ cluster_name }}-cluster"
        clientSecret: "{{ client_secret.resources[0].data.CLIENT_SECRET | b64decode }}"
        keycloakUrl: "{{ keycloak_url }}"

    - name: deploy groupsync secret
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster_secret['kubeconfig'] }}"
        definition:
          kind: Secret
          api_version: v1
          metadata:
            name: "helms-deep-group-sync-credentials"
            namespace: helms-deep
          data:
            username: "{{ groupsync_credentials.resources[0].data.username }}"
            password: "{{ groupsync_credentials.resources[0].data.password }}"
          type: Opaque

    - name: deploy GroupSync resource
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster_secret['kubeconfig'] }}"
        definition: "{{ lookup('template', 'templates/sso/groupsync.yaml.j2') }}"
      vars:
        cluster_groups:
          - "{{ cluster_name }}-cluster-admins"
          - "{{ cluster_name }}-auditors"
          - "{{ cluster_name }}-developers"
        sync_groups: "{{ cluster_groups + ( groupsync_common_groups | default([]) ) }}"
      register: gs
      until:
        - not gs.failed
      delay: 10
      retries: 30
