---
- name: "get cluster DNS from satellite cluster {{ cluster_name }}"
  community.kubernetes.k8s_info:
    host: "{{ cluster_secret['server'] }}"
    api_key: "{{ cluster_secret['token'] }}"
    validate_certs: "{{ not cluster_secret['insecure'] }}"
    api_version: config.openshift.io/v1
    kind: DNS
    namespace: openshift-config
    name: cluster
  register: cluster_dns
  
- set_fact:
		sat_cluster_basedomain: "{{ cluster_dns.resources[0].spec.baseDomain }}"

- include_tasks: "tasks/sso/create-client-and-secret.yaml"
  vars:
    clientName: "{{ cluster_name }}-cluster"
    rootUrk: 'https://console-openshift-console.apps.{{ sat_cluster_basedomain }}'
    validRedirectURIs:
      - 'https://console-openshift-console.apps.{{ sat_cluster_basedomain }}/*'
      - 'https://api.{{ sat_cluster_basedomain }}/*'
      - 'https://oauth-openshift.apps.{{ sat_cluster_basedomain }}/*'

- debug: var=client_secret
