---
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  namespace: open-cluster-management
  name: multiclusterhub
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec: {}

