- name: "sso - create KeycloakClient client_name={{ clientName }}"
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'templates/sso/keycloakclient.yaml.j2') | from_yaml }}"

- name: "sso - wait for KeycloakClient/{{ client_name }} to reconcile (5 minutes)"
  community.kubernetes.k8s_info:
    api_version: keycloak.org/v1alpha1
    kind: KeycloakClient
    namespace: helms-deep-sso
    name: "{{ clientName }}"
  register: client
  until:
  - client.resources|length > 0
  - client.resources[0].status is defined
  - client.resources[0].status.phase == 'reconciling'
  retries: 10
  delay: 30

- name: sso - fetch cluster OAuth client secret
  community.kubernetes.k8s_info:
    api_version: v1
    kind: Secret
    namespace: helms-deep-sso
    name: "{{ client.resources[0].status.secondaryResources.Secret[0] }}"
  register: client_secret
