kind: Secret
apiVersion: v1
metadata:
  name: aws-credentials
  namespace: {{ namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "20"
data:
  credentials: {{ lookup('template', 'aws-credential-secret.properties.yaml') | b64encode }}
type: Opaque
