apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: advanced-cluster-security
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ''
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/acs
    repoURL: git@github.com:adamgoossens/helms-deep.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
